FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["GreenhouseFactoryService/GreenhouseFactoryService.csproj", "GreenhouseFactoryService/"]
RUN dotnet restore "GreenhouseFactoryService/GreenhouseFactoryService.csproj"
COPY . .
RUN dotnet build "GreenhouseFactoryService/GreenhouseFactoryService.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "GreenhouseFactoryService/GreenhouseFactoryService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GreenhouseFactoryService.dll"]