services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ broker port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - greenhouse-net

  postgres-db:
    image: postgres:18
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: greenhouse
      POSTGRES_PASSWORD: greenhouse123
      POSTGRES_DB: greenhouse
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greenhouse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - greenhouse-net

  greenhousefactoryservice:
    build:
      context: ./GreenhouseFactoryService
      dockerfile: Dockerfile
    container_name: greenhousefactoryservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    networks:
      - greenhouse-net
    ports:
      - "5002:8080"
    environment:
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=greenhouse;Username=greenhouse;Password=greenhouse123

  simulatorui:
    build:
      context: ./SimulatorUI
      dockerfile: Dockerfile
    container_name: simulatorui
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - greenhouse-net
    ports:
      - "5003:8080"
    environment:
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672

  soilmoistureservice:
    build:
      context: ./SoilMoistureService
      dockerfile: Dockerfile
    container_name: soilmoistureservice
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - greenhouse-net
    ports:
      - "5004:8080"
    environment:
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672

  waterservice:
    build:
      context: ./WaterService
      dockerfile: Dockerfile
    container_name: waterservice
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - greenhouse-net
    ports:
      - "5005:8080"
    environment:
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
      args:
        REACT_APP_FACTORY_API: http://host.docker.internal:5002
        REACT_APP_WATER_API: http://host.docker.internal:5005
    container_name: dashboard
    depends_on:
      greenhousefactoryservice:
        condition: service_started
      waterservice:
        condition: service_started
    networks:
      - greenhouse-net
    ports:
      - "5006:80"

networks:
  greenhouse-net:
    driver: bridge
