@startuml

node "Docker Host" {
    node "Simulator UI\n.NET\nPort 5003" as SimulatorUI {
    }
    node "SoilMoistureService\n.NET\nPort 5004" as SoilService {
    }
    node "WaterService\n.NET\nPort 5005" as WaterService {
    }
    node "GreenHouseFactoryService\n.NET\nPort 5002" as GreenHouseService {
    }
    node "Dashboard\nReact\nPort 5006" as Dashboard {
    }
    database "PostgreSQL\nDocker\nPort 5432" as DB {
    }
    node "MessageBus\nRabbitMQ\nPort 5672" as RabbitMQ {
    }
}

SimulatorUI --> RabbitMQ : AMQP

SoilService --> RabbitMQ : AMQP
RabbitMQ --> SoilService : AMQP

RabbitMQ --> WaterService : AMQP
WaterService -> Dashboard : HTTP WebSockets Port 80

RabbitMQ --> GreenHouseService : AMQP
GreenHouseService --> DB : TCP
Dashboard --> GreenHouseService : HTTP

@enduml
