@startuml
skinparam sequence {
    ParticipantBackgroundColor #eef2f7
    ParticipantBorderColor #4a4a4a
    ActorBorderColor #4a4a4a
    ActorBackgroundColor #eef2f7
}

participant Dashboard <<UI>>
participant "GreenhouseFactoryService" as FactoryService <<Microservice>>
participant SimulatorUI <<UI>>
participant SoilMoistureService <<Microservice>>
participant WaterService <<Microservice>>
participant "RabbitMQ Bus" as MessageBus <<MessageBus>>

' --- Init factories ---
activate FactoryService
FactoryService -> FactoryService: Auto-generate factories\nwith greenhouses
deactivate FactoryService

Dashboard -> FactoryService: GET /factory/all

activate FactoryService
FactoryService --> Dashboard
deactivate FactoryService

SimulatorUI --> MessageBus: SoilMoistureEvent(factoryId,\ngreenhouseId, percentage)
MessageBus --> SoilMoistureService: SoilMoistureEvent(factoryId,\ngreenhouseId, percentage)

activate SoilMoistureService
SoilMoistureService --> SoilMoistureService: ProcessAsync(int factoryId, \nint greenhouseId, \nsoilMoisturePercentage)
deactivate SoilMoistureService

SoilMoistureService --> MessageBus: WaterEvent(int factoryId, \n int greenhouseId,\n bool waterOn)

MessageBus --> FactoryService: WaterEvent(int factoryId,\n int greenhouseId,\n bool waterOn)

activate FactoryService
FactoryService --> FactoryService: AddWaterAsync(int factoryId, \n int greenhouseId, \n bool waterOn)
deactivate FactoryService

MessageBus --> WaterService: WaterEvent(int factoryId, \n int greenhouseId,\n bool waterOn)

WaterService --> Dashboard: WaterStatusChanged(int factoryId,\n int greenhouseId,\nbool waterOn)

@enduml
